### ISSUE TITLE
Dynamically add items to component's state, it does not update the columns?

### ISSUE THREAD

**Issue by yihou** [novascreen/react-columns#11]
currently, I have a list of items being add-in dynamically in the component's state, but the columns are not updated until I resizing the page. Is there a way to update the columns after the list of items changed?

**Comment by yihou** [comment]
Sorry I found a fix, I was not using `this.setState()` that's the reason why the columns are not updated.

**Comment by chadspencer** [comment]
@yihou Could you share your solution for this? Running into the same problem.

**Comment by yihou** [comment]
@chadspencer sorry for late reply, as for the bug I met is due to my coding error.
Another thing that I find that this component won't refresh the value once the `queries` value changes,
and how can I help you? Any reference code to look at?

**Comment by novascreen** [comment]
@yihou thanks for offering your help. Btw. the `queries` problem was reported and addressed in #19

**Comment by yihou** [comment]
@novascreen alright, cheers.
