### ISSUE TITLE
Isormorphic app - css problem

### ISSUE THREAD

**Issue by Jaikant** [novascreen/react-columns#12]
In my Isomorphic app, when the column loads. The cards which are in react-column have more number of columns, before taking on the value in queries.  Any help on this?

**Comment by novascreen** [comment]
Since there are no media queries on the server the component renders as many columns as is set in the `columns` prop, which defaults to `3`. You should be able to change that to adjust the columns on the server, before the media queries take over on the client.

**Comment by novascreen** [comment]
Closing this. Let me know if you run into any more issues.
