### ISSUE TITLE
Upgrade to prop-types

### ISSUE THREAD

**Issue by zachariahtimothy** [novascreen/react-columns#18]
Nice work on a react package that works as expected!
Any chance there is a plan to change PropTypes from react to the prop-types library?

**Comment by novascreen** [comment]
hey @zachariahtimothy  would you be interested in doing a PR?
otherwise i'll see that i update it shortly

**Comment by novascreen** [comment]
@zachariahtimothy published 1.1.0 with the change

**Comment by zachariahtimothy** [comment]
Thanks a bunch @novascreen ! Sorry I had a busy week and did not get a chance for a PR.
